# -*- coding: utf-8 -*-

# OPENROUTER - ONLY LLM PROVIDER
OPENROUTER_API_KEYS = "key1,key2,key3"
OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1"
OPENROUTER_MODEL = "nvidia/nemotron-3-ultra-550b-a55b:free"

# MISTRAL - EMBEDDINGS ONLY
EMB_API_KEYS = "key1,key2,key3"
EMB_BASE_URL = "https://api.mistral.ai/v1"
EMB_MODEL = "mistral-embed"
EMB_DIM = 1024

# ADAPTIVE HYPER-RAG ROUTING
ADAPTIVE_RAG_ENABLED = True
ADAPTIVE_RAG_MODE = "adaptive"
ADAPTIVE_CORE_THRESHOLD = 60
ADAPTIVE_RETRIEVAL_SUFFICIENCY_ENABLED = True
ADAPTIVE_RETRIEVAL_SUFFICIENCY_THRESHOLD = 60
ADAPTIVE_LOG_DECISIONS = True
ADAPTIVE_SHORT_QUERY_MAX_WORDS = 7
ADAPTIVE_SHORT_QUERY_DENSITY_BONUS = 15.0

# PHASE 3 - RESPONSE VALIDATION
ADAPTIVE_VALIDATION_ENABLED = True
ADAPTIVE_VALIDATION_THRESHOLD = 70.0
ADAPTIVE_VALIDATION_LOG_DECISIONS = True
ADAPTIVE_VALIDATION_COMPLETENESS_WEIGHT = 0.40
ADAPTIVE_VALIDATION_EVIDENCE_WEIGHT = 0.40
ADAPTIVE_VALIDATION_RELEVANCE_WEIGHT = 0.20
